# object detector boot.py
# generated by maixhub.com

import sensor, image, lcd, time
import KPU as kpu
import gc, sys
import uos
from fpioa_manager import fm
from Maix import GPIO
from dht11 import DHT11
import ujson
from machine import UART

fm.register(7, fm.fpioa.GPIOHS3, force=True)
#fm.register(6, fm.fpioa.GPIO6, force=True)
fm.register(25, fm.fpioa.UART2_TX, force=True)
fm.register(24, fm.fpioa.UART2_RX, force=True)

gpio7 = GPIO(GPIO.GPIOHS3, GPIO.OUT)
#sw_esp = GPIO(GPIO.GPIO6, GPIO.OUT)
uart_esp = UART(UART.UART2, 115200, 8, 0, 0, timeout=1000, read_buf_len=4096)
dht = DHT11(gpio7)


def send_data_uart():
    #combine all data
    data = {"temp":20,"hum":30,"fire":40,"smoke":50}
    payload = ujson.dumps(data)
    uart_esp.write(payload)
    #print(payload)
    time.sleep(2)

if __name__ == "__main__":
    while True:
        send_data_uart()

